/*****************************************************************************
 * This file was generated automatically by Parser.
 * Do not edit this file manually.
 * 
 * This file was generated using Parser-1.0.0 compiled in May  9 2009 15:49:39
 * 
 * File created in 2009-05-16 13:29:38
 *****************************************************************************/

#ifndef GRAMMARLOADERPARSERBUFFER_H
#define GRAMMARLOADERPARSERBUFFER_H

enum GrammarLoaderParserBuffer_tokens {
	GRAMMARLOADERPARSERBUFFER_TOKEN_COMMENT = 0,
	GRAMMARLOADERPARSERBUFFER_TOKEN_NON_TERMINAL = 1,
	GRAMMARLOADERPARSERBUFFER_TOKEN_OR = 4,
	GRAMMARLOADERPARSERBUFFER_TOKEN_REDUCE = 2,
	GRAMMARLOADERPARSERBUFFER_TOKEN_RULE_END = 3,
	GRAMMARLOADERPARSERBUFFER_TOKEN_TOKEN = 5,
	GRAMMARLOADERPARSERBUFFER_TOKEN_WHITESPACE = 6
};

extern unsigned char parser_loader_buffer_scanner[];
extern unsigned int parser_loader_buffer_scanner_size;

#endif
