/*****************************************************************************
 * This file was generated automatically by Parser.
 * Do not edit this file manually.
 * 
 * This file was generated using Parser-1.0.0 compiled in May  9 2009 15:49:39
 * 
 * File created in 2009-05-16 13:29:38
 *****************************************************************************/

#ifndef REGEXLOADERBUFFER_H
#define REGEXLOADERBUFFER_H

enum RegexLoaderBuffer_tokens {
	REGEXLOADERBUFFER_TOKEN_CLOSURE = 0,
	REGEXLOADERBUFFER_TOKEN_COMPOSED_END = 6,
	REGEXLOADERBUFFER_TOKEN_COMPOSED_START = 5,
	REGEXLOADERBUFFER_TOKEN_NOT = 4,
	REGEXLOADERBUFFER_TOKEN_ONE_CLOSURE = 1,
	REGEXLOADERBUFFER_TOKEN_OPTIONAL = 2,
	REGEXLOADERBUFFER_TOKEN_OR = 3,
	REGEXLOADERBUFFER_TOKEN_SYMBOL = 9,
	REGEXLOADERBUFFER_TOKEN_SYMBOL_LIST_END = 8,
	REGEXLOADERBUFFER_TOKEN_SYMBOL_LIST_START = 7
};

enum RegexLoaderBuffer_nonTerminals {
	REGEXLOADERBUFFER_NONTERMINAL_EXPRESSION = 2,
	REGEXLOADERBUFFER_NONTERMINAL_FACTOR = 3,
	REGEXLOADERBUFFER_NONTERMINAL_REGEX = 0,
	REGEXLOADERBUFFER_NONTERMINAL_REGEX_OR = 1,
	REGEXLOADERBUFFER_NONTERMINAL_SYMBOL_LIST = 5,
	REGEXLOADERBUFFER_NONTERMINAL_SYMBOL_SET = 4
};

extern unsigned char regex_loader_buffer_scanner[];
extern unsigned int regex_loader_buffer_scanner_size;

extern unsigned char regex_loader_buffer_parser[];
extern unsigned int regex_loader_buffer_parser_size;

#endif
